// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ShortageSimulation.ShortageEF
{
    public partial class FinishedGoods
    {
        public int Fid { get; set; }
        public string Fname { get; set; }
        public string Mname { get; set; }
        public int? Usage { get; set; }
    }
}