// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ShortageSimulation.ShortageEF
{
    public partial class Materials
    {
        public int Id { get; set; }
        public string Mname { get; set; }
        public int? Stocks { get; set; }
    }
}